/// Flutter icons Icones_per
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icones_per
///      fonts:
///       - asset: fonts/Icones_per.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Icomoon {
  Icomoon._();

  static const _kFontFam = 'icomoon';
  static const _kFontPkg = null;

  static const IconData a = IconData(0xea07, fontFamily: 'icomoon');
  static const IconData b = IconData(0xea4f, fontFamily: 'icomoon');
}
